### ISSUE TITLE
Failure to load the action

### ISSUE THREAD

**Issue by pnmadelaine** [flakestry/flakestry-publish#3]
When trying to use the action, I get the following error:
```
Download action repository 'flakestry/flakestry-publish@main' (SHA:fd80e4c1432592211aa496126a14d8dbfdd5b373)
Error: flakestry/flakestry-publish/main/action.yaml (Line: 29, Col: 12): Unexpected symbol: '"false"'. Located at position 27 within expression: inputs.ignoreConflicts || "false"
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. flakestry/flakestry-publish/main/action.yaml (Line: 29, Col: 12): Unexpected symbol: '"false"'. Located at position 27 within expression: inputs.ignoreConflicts || "false"
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load flakestry/flakestry-publish/main/action.yaml
```

My exact workflow is:
```yaml
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: "The existing reference to publish"
        type: "string"
        required: true
jobs:
  publish-flake:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: flakestry/flakestry-publish@main
        with:
          ref: "${{ inputs.ref || github.ref }}"
          url: https://staging.flakestry.dev

```

**Comment by imincik** [comment]
I see the same issue in my repo.
